// Pricing content inventory — packages/prices/features mirrored from the
// reference site (americanwebbuilders.com) per the client's request; only
// exact-duplicate lines from the source markup were removed. The middle
// package of each category is flagged `popular`.

export interface PricingGroup {
  heading: string;
  items: string[];
}

export interface PricingPackage {
  name: string;
  price: string;
  original: string;
  /** flat feature list (non-grouped packages) */
  features?: string[];
  /** grouped feature list (SEO packages) */
  groups?: PricingGroup[];
  popular?: boolean;
}

export interface PricingCategory {
  key: string;
  tab: string;
  title: string;
  note: string;
  packages: [PricingPackage, PricingPackage, PricingPackage];
}

export const PRICING_HEADING = "Better Packages, Better Prices";

const RUSH = "*Rush Delivery = $500";

export const PRICING_CATEGORIES: PricingCategory[] = [
  {
    key: "web",
    tab: "Web",
    title: "Website Design Packages",
    note: RUSH,
    packages: [
      {
        name: "Basic Plan",
        price: "$349",
        original: "$580",
        features: [
          "3 Page Website",
          "2 Stock Images",
          "1 jQuery Slider Banner",
          "Contact/Query Form",
          "48 to 72 hours TAT",
          "Complete Development",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
          "Conceptual and Dynamic Website",
          "Mobile Responsive",
          "Online Reservation/Appointment Tool (Optional)",
          "Online Payment Integration (Optional)",
          "Custom Forms",
          "Lead Capturing Forms (Optional)",
          "Newsletter Subscription (Optional)",
          "Newsfeed Integration",
          "CMS / Admin Panel Support",
          "Social Media Integration",
        ],
      },
      {
        name: "Professional",
        price: "$689",
        original: "$1199",
        popular: true,
        features: [
          "10 Unique Pages Website",
          "CMS / Admin Panel Support",
          "12 Stock images",
          "5 Banner Designs",
          "1 jQuery Slider Banner",
          "FREE Google Friendly Sitemap",
          "48 to 72 hours TAT",
          "Complete Deployment",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
          "Conceptual and Dynamic Website",
          "Mobile Responsive",
          "Online Reservation/Appointment Tool (Optional)",
          "Online Payment Integration (Optional)",
          "Custom Forms",
          "Lead Capturing Forms (Optional)",
          "Striking Hover Effects",
          "Newsletter Subscription (Optional)",
          "Newsfeed Integration",
        ],
      },
      {
        name: "Elite",
        price: "$1299",
        original: "$1850",
        features: [
          "Upto 15 Unique Pages Website",
          "Conceptual and Dynamic Website",
          "Mobile Responsive",
          "Online Reservation/Appointment Tool (Optional)",
          "Online Payment Integration (Optional)",
          "Custom Forms",
          "Lead Capturing Forms (Optional)",
          "Striking Hover Effects",
          "Newsletter Subscription (Optional)",
          "Newsfeed Integration",
          "Social Media Integration",
          "Search Engine Submission",
          "5 Stock Photos",
          "3 Unique Banner Design",
          "1 jQuery Slider Banner",
          "48 to 72 hours TAT",
          "Complete Deployment",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
        ],
      },
    ],
  },
  {
    key: "ecommerce",
    tab: "E-Commerce",
    title: "E-Commerce Packages",
    note: RUSH,
    packages: [
      {
        name: "Kickstarter",
        price: "$600",
        original: "$1,200",
        features: [
          "Up-to 100 Products",
          "Content Management System (CMS)",
          "Mini Shopping Cart Integration",
          "Payment Module Integration",
          "Easy Product Search",
          "Dedicated designer & developer",
          "Unlimited Revisions",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
          "Customized Design",
          "Full Shopping Cart Integration",
          "Product Reviews",
          "5 Promotional Banners",
          "Team of Expert Designers & Developers",
          "Unlimited Pages Website with Unique Design",
          "UNLIMITED Logo Design Concepts",
          "By 6 Award Winning Designers",
          "Icon Design",
          "Stationary Design (BusinessCard, Letterhead & Envelope)",
          "Invoice Design, Email Signature",
          "Bi-Fold Brochure (OR) 2 Sided Flyer Design",
          "Sign age Design (OR) Label Design",
          "T-Shirt Design (OR) Car Wrap Design",
          "E-Commerce Store Design",
          "Product Detail Page Design",
          "Unique Banner Slider",
          "Featured Products Showcase",
          "Unlimited Products",
          "Unlimited Categories",
          "Multi-currency Support",
          "Customer Log-in Area",
          "Mobile Responsive",
          "Social Media Plugins Integration",
          "Tell a Friend Feature",
          "Facebook, Twitter, YouTube, Google+ & Pinterest Page Designs",
          "Dedicated Account Manager",
        ],
      },
      {
        name: "Dynamic",
        price: "$1,394",
        original: "$2,788",
        popular: true,
        features: [
          "Customized Design",
          "Up-to 500 Products",
          "Content Management System (CMS)",
          "Full Shopping Cart Integration",
          "Payment Module Integration",
          "Easy Product Search",
          "Product Reviews",
          "5 Promotional Banners",
          "Team of Expert Designers & Developers",
          "Unlimited Revisions",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
          "Unlimited Pages Website with Unique Design",
          "UNLIMITED Logo Design Concepts",
          "By 6 Award Winning Designers",
          "Icon Design",
          "Stationary Design (BusinessCard, Letterhead & Envelope)",
          "Invoice Design, Email Signature",
          "Bi-Fold Brochure (OR) 2 Sided Flyer Design",
          "Product Catalog Design",
          "Sign age Design (OR) Label Design",
          "T-Shirt Design (OR) Car Wrap Design",
          "E-Commerce Store Design",
          "Product Detail Page Design",
          "Unique Banner Slider",
          "Featured Products Showcase",
          "Unlimited Products",
          "Unlimited Categories",
          "Multi-currency Support",
          "Customer Log-in Area",
          "Mobile Responsive",
          "Social Media Plugins Integration",
          "Tell a Friend Feature",
          "Facebook, Twitter, YouTube, Google+ & Pinterest Page Designs",
          "Dedicated Account Manager",
        ],
      },
      {
        name: "High-End",
        price: "$3,694",
        original: "$7,388",
        features: [
          "Unlimited Pages Website with Unique Design",
          "UNLIMITED Logo Design Concepts",
          "By 6 Award Winning Designers",
          "Icon Design",
          "UNLIMITED Revisions",
          "Stationary Design (BusinessCard, Letterhead & Envelope)",
          "Invoice Design, Email Signature",
          "Bi-Fold Brochure (OR) 2 Sided Flyer Design",
          "Product Catalog Design",
          "Sign age Design (OR) Label Design",
          "T-Shirt Design (OR) Car Wrap Design",
          "E-Commerce Store Design",
          "Product Detail Page Design",
          "Unique Banner Slider",
          "Featured Products Showcase",
          "Full Shopping Cart Integration",
          "Unlimited Products",
          "Unlimited Categories",
          "Product Rating & Reviews",
          "Easy Product Search",
          "Payment Gateway Integration",
          "Multi-currency Support",
          "Content Management System",
          "Customer Log-in Area",
          "Mobile Responsive",
          "Social Media Plugins Integration",
          "Tell a Friend Feature",
          "Facebook, Twitter, YouTube, Google+ & Pinterest Page Designs",
          "Dedicated Account Manager",
          "All Final File Formats",
          "100% Ownership Rights",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
        ],
      },
    ],
  },
  {
    key: "logo",
    tab: "Logo",
    title: "Logo Design Packages",
    note: RUSH,
    packages: [
      {
        name: "Basic",
        price: "$39",
        original: "$120",
        features: [
          "2 Custom Logo Design Concepts",
          "1 Dedicated Designer",
          "4 REVISIONS",
          "48 to 72 hours TAT",
          "100% Unique Design Guarantee",
          "100% Satisfaction Guarantee",
          "100% Ownership Rights",
          "100% Money Back Guarantee",
          "Stationary Design (Business Card, Letterhead, Envelope)",
          "FREE MS Word Letterhead",
          "All Final Files Format (AI, PSD, EPS, PNG, GIF, jpeg, PDF)",
        ],
      },
      {
        name: "Startup",
        price: "$79",
        original: "$250",
        popular: true,
        features: [
          "5 Custom Logo Design Concepts",
          "By 2 Designers",
          "UNLIMITED Revisions",
          "48 to 72 hours TAT",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Ownership Rights",
          "100% Money Back Guarantee",
          "Stationary Design (Business Card, Letterhead, Envelope)",
          "FREE MS Word Letterhead",
          "All Final Files Format (AI, PSD, EPS, PNG, GIF, jpeg, PDF)",
        ],
      },
      {
        name: "Professional",
        price: "$129",
        original: "$410",
        features: [
          "UNLIMITED Logo Design Concepts",
          "By 4 Designers",
          "UNLIMITED Revisions",
          "Stationary Design (Business Card, Letterhead, Envelope)",
          "48 to 72 hours TAT",
          "FREE MS Word Letterhead",
          "All Final Files Format (AI, PSD, EPS, PNG, GIF, jpeg, PDF)",
          "100% Satisfaction Guarantee",
          "100% Unique Design Guarantee",
          "100% Ownership Rights",
          "100% Money Back Guarantee",
        ],
      },
    ],
  },
  {
    key: "seo",
    tab: "SEO",
    title: "SEO Packages",
    note: RUSH,
    packages: [
      {
        name: "Startup Plan",
        price: "$350",
        original: "$700",
        groups: [
          {
            heading: "Prior Analysis",
            items: [
              "Domain Overview",
              "Website Audit",
              "Business Analysis",
              "Consumer Analysis",
              "Competitor Analysis",
              "15 selected Keyword Targeting",
              "15 page Keyword Targeting",
            ],
          },
          {
            heading: "ON Page Optimization",
            items: [
              "Meta tag creation",
              "Keyword Optimization",
              "Image Optimization",
              "Inclusion of anchors",
              "Webpage Optimization",
              "Call To Action Plan",
              "Creation of Sitemaps",
              "Creation of Robots.txt",
            ],
          },
          {
            heading: "Off Page Optimization",
            items: [
              "Social Bookmarking",
              "Slide Share Marketing",
              "Forums/FAQ's",
              "Link Building",
              "Directory Submission",
            ],
          },
          {
            heading: "Tracking & Analysis",
            items: [
              "Google Analytics Installation",
              "Google Webmaster Installation",
              "Indexing Modifications",
            ],
          },
          {
            heading: "Reporting",
            items: [
              "Monthly Reporting",
              "Recommendation",
              "Email Support",
              "Phone Support",
            ],
          },
        ],
      },
      {
        name: "Scaling Plan",
        price: "$700",
        original: "$1,400",
        popular: true,
        groups: [
          {
            heading: "Prior Analysis",
            items: [
              "Domain Overview",
              "Website Audit",
              "Business analysis",
              "Consumer analysis",
              "Competitor Analysis",
              "30 selected Keyword Targeting",
            ],
          },
          {
            heading: "ON Page Optimization",
            items: [
              "Meta tag creation",
              "Keyword Optimization",
              "Image Optimization",
              "Inclusion of anchors tag",
              "Indexing Modifications",
              "Creation of Sitemaps",
              "Creation of Robots.txt",
              "Google places inclusions",
              "Call To Action Plan",
            ],
          },
          {
            heading: "Campaign Setup & Optimization",
            items: [
              "Pages Optimized (10 pages)",
              "Keyword Research",
              "Keyword Grouping",
              "Keyword Mapping",
              "SEO Road Map",
              "Blog Creation",
              "Webpage Copywriting (3 pages, 350 words per page)",
              "Title Tag Optimization (10 titles)",
              "Meta Description Optimization (10 meta description)",
              "Meta Keyword Optimization (10 meta keywords)",
              "Domain Redirect Optimization (10 domain redirects)",
              "xml Sitemap Optimization",
              "Robots.txt Check",
              "URL Rewrites (10 URL rewrites)",
              "Broken Link Report",
              "Rich Snippet Recommendations",
              "Breadcrumbs",
              "Initial Off-Page SEO",
            ],
          },
          {
            heading: "Off Page Optimization",
            items: [
              "Social Bookmarking",
              "Slide Share Marketing",
              "Forums/FAQ's",
              "Link Building",
              "Directory Submission",
            ],
          },
          {
            heading: "Reporting",
            items: [
              "Monthly Reporting",
              "Recommendation",
              "Email Support",
              "Phone Support",
            ],
          },
        ],
      },
      {
        name: "Venture Plan",
        price: "$1200",
        original: "$2,400",
        groups: [
          {
            heading: "Prior Analysis",
            items: [
              "Domain Overview",
              "Website Audit",
              "Business analysis",
              "Consumer analysis",
              "Competitor Analysis",
              "70 selected Keyword Targeting",
              "50 selected Keyword Targeting",
            ],
          },
          {
            heading: "ON Page Optimization",
            items: [
              "Meta tag creation",
              "Keyword Optimization",
              "Image Optimization",
              "Inclusion of anchors tag",
              "Indexing Modifications",
              "Creation of Sitemaps",
              "Creation of Robots.txt",
              "Google places inclusions",
              "Call To Action Plan",
            ],
          },
          {
            heading: "Off Page Optimization",
            items: [
              "Social Bookmarking",
              "Slide Share Marketing",
              "Forums/FAQ's",
              "Link Building",
              "Directory Submission",
              "Local Business Listings",
            ],
          },
          {
            heading: "Reporting",
            items: [
              "Monthly Reporting",
              "Recommendation",
              "Email Support",
              "Phone Support",
            ],
          },
        ],
      },
    ],
  },
  {
    key: "branding",
    tab: "Branding",
    title: "Branding Packages",
    note: RUSH,
    packages: [
      {
        name: "Stationary",
        price: "$99",
        original: "$370",
        features: [
          "1 Business Card Design",
          "1 Letterhead Design",
          "1 Envelope Design",
          "Dedicated Designer",
          "3 Design Revisions",
          "Turnaround Time 24 - 48 Hours",
          "100% Satisfaction Guaranteed",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
          "All Final File Formats",
        ],
      },
      {
        name: "Brochure/Flyer",
        price: "$149",
        original: "$979",
        popular: true,
        features: [
          "2 Design Concepts (Trifold / Bi-fold)",
          "Dedicated Designer",
          "Dedicated Account Manager",
          "Unlimited Revisions",
          "Turnaround Time - 48 - 72 Hours",
          "100% Satisfaction Guaranteed",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
          "All Final File Formats",
        ],
      },
      {
        name: "Poster Design",
        price: "$299",
        original: "$700",
        features: [
          "1 Unique Design",
          "3 Design Concepts",
          "Dedicated Designer",
          "2 Design Revisions",
          "Turnaround Time - 48 - 72 Hours",
          "100% Satisfaction Guaranteed",
          "100% Unique Design Guarantee",
          "100% Money Back Guarantee",
          "All Final File Formats",
        ],
      },
    ],
  },
  {
    key: "smm",
    tab: "SMM",
    title: "Social Media Marketing Packages",
    note: RUSH,
    packages: [
      {
        name: "Basic",
        price: "$750",
        original: "$1500",
        features: [
          "12/Month Unique Social Media Content Posting",
          "Social Media Analysis",
          "Page Optimization",
          "Social Media Marketing Plan",
          "Post Design Scheduling",
          "Profile Keyword Optimization - 3 Keywords",
          "Performance Report",
          "2 Platforms",
        ],
      },
      {
        name: "Standard",
        price: "$1000",
        original: "$2000",
        popular: true,
        features: [
          "20/Month Unique Social Media Content Posting",
          "Competitor Analysis",
          "Community Management",
          "Page Moderation",
          "Social Media Strategy",
          "Page Monitoring & Responding",
          "Social Media Analysis",
          "Page Optimization",
          "Social Media Marketing Plan",
          "Post Design Scheduling",
          "Profile Keyword Optimization - 6 Keywords",
          "Performance Report",
          "4 Platforms",
        ],
      },
      {
        name: "Prime",
        price: "$1200",
        original: "$2400",
        features: [
          "40/Month Unique Social Media Content Posting",
          "Competitor Analysis",
          "Community Management",
          "Page Moderation",
          "Page Monitoring & Responding",
          "Social Media Analysis",
          "Page Optimization",
          "Social Media Marketing Plan",
          "Post Design Scheduling",
          "Profile Keyword Optimization - 8 Keywords",
          "Performance Report",
          "Unlimited Platforms",
        ],
      },
    ],
  },
];
